<?php 

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_profil_companie',
	'title' => 'Profil	Companie',
	'fields' => array(
		array(
			'key' => 'field_5d09e5f99b0e1',
			'label' => 'Date companie',
			'name' => 'date_companie2',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'layout' => 'row',
			'sub_fields' => array(
				array(
					'key' => 'field_5d09e5f9a082d',
					'label' => 'Nume',
					'name' => 'nume_companie',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => 'Nume',
					'prepend' => '',
					'append' => '',
					'maxlength' => 40,
				),
				array(
					'key' => 'field_5d09e5f9a0876',
					'label' => 'Nume alternativ',
					'name' => 'nume_alternativ',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => 'Nume alternativ',
					'prepend' => '',
					'append' => '',
					'maxlength' => 40,
				),
				array(
					'key' => 'field_5d09e5f9a08b8',
					'label' => 'Orgine',
					'name' => 'origine',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'Afghanistan' => 'Afghanistan',
						'Albania' => 'Albania',
						'Algeria' => 'Algeria',
						'America' => 'America',
						'Andorra' => 'Andorra',
						'Angola' => 'Angola',
						'Antigua' => 'Antigua',
						'Argentina' => 'Argentina',
						'Armenia' => 'Armenia',
						'Australia' => 'Australia',
						'Austria' => 'Austria',
						'Azerbaijan' => 'Azerbaijan',
						'Bahamas' => 'Bahamas',
						'Bahrain' => 'Bahrain',
						'Bangladesh' => 'Bangladesh',
						'Barbados' => 'Barbados',
						'Belarus' => 'Belarus',
						'Belgium' => 'Belgium',
						'Belize' => 'Belize',
						'Benin' => 'Benin',
						'Bhutan' => 'Bhutan',
						'Bissau' => 'Bissau',
						'Bolivia' => 'Bolivia',
						'Bosnia' => 'Bosnia',
						'Botswana' => 'Botswana',
						'Brazil' => 'Brazil',
						'British' => 'British',
						'Brunei' => 'Brunei',
						'Bulgaria' => 'Bulgaria',
						'Burkina' => 'Burkina',
						'Burma' => 'Burma',
						'Burundi' => 'Burundi',
						'Cambodia' => 'Cambodia',
						'Cameroon' => 'Cameroon',
						'Canada' => 'Canada',
						'Cape Verde' => 'Cape Verde',
						'Central African Republic' => 'Central African Republic',
						'Chad' => 'Chad',
						'Chile' => 'Chile',
						'China' => 'China',
						'Colombia' => 'Colombia',
						'Comoros' => 'Comoros',
						'Congo' => 'Congo',
						'Costa Rica' => 'Costa Rica',
						'Croatia' => 'Croatia',
						'Cuba' => 'Cuba',
						'Cyprus' => 'Cyprus',
						'Czech' => 'Czech',
						'Denmark' => 'Denmark',
						'Djibouti' => 'Djibouti',
						'Dominica' => 'Dominica',
						'East Timor' => 'East Timor',
						'Ecuador' => 'Ecuador',
						'Egypt' => 'Egypt',
						'El Salvador' => 'El Salvador',
						'Emirate' => 'Emirate',
						'England' => 'England',
						'Eritrea' => 'Eritrea',
						'Estonia' => 'Estonia',
						'Ethiopia' => 'Ethiopia',
						'Fiji' => 'Fiji',
						'Finland' => 'Finland',
						'France' => 'France',
						'Gabon' => 'Gabon',
						'Gambia' => 'Gambia',
						'Georgia' => 'Georgia',
						'Germany' => 'Germany',
						'Ghana' => 'Ghana',
						'Great Britain' => 'Great Britain',
						'Greece' => 'Greece',
						'Grenada' => 'Grenada',
						'Grenadines' => 'Grenadines',
						'Guatemala' => 'Guatemala',
						'Guinea' => 'Guinea',
						'Guyana' => 'Guyana',
						'Haiti' => 'Haiti',
						'Herzegovina' => 'Herzegovina',
						'Holland' => 'Holland',
						'Honduras' => 'Honduras',
						'Hungary' => 'Hungary',
						'Iceland' => 'Iceland',
						'India' => 'India',
						'Indonesia' => 'Indonesia',
						'Iran' => 'Iran',
						'Iraq' => 'Iraq',
						'Ireland' => 'Ireland',
						'Israel' => 'Israel',
						'Italy' => 'Italy',
						'Ivory Coast' => 'Ivory Coast',
						'Jamaica' => 'Jamaica',
						'Japan' => 'Japan',
						'Jordan' => 'Jordan',
						'Kazakhstan' => 'Kazakhstan',
						'Kenya' => 'Kenya',
						'Kiribati' => 'Kiribati',
						'Korea' => 'Korea',
						'Kosovo' => 'Kosovo',
						'Kuwait' => 'Kuwait',
						'Kyrgyzstan' => 'Kyrgyzstan',
						'Laos' => 'Laos',
						'Latvia' => 'Latvia',
						'Lebanon' => 'Lebanon',
						'Lesotho' => 'Lesotho',
						'Liberia' => 'Liberia',
						'Libya' => 'Libya',
						'Liechtenstein' => 'Liechtenstein',
						'Lithuania' => 'Lithuania',
						'Luxembourg' => 'Luxembourg',
						'Macedonia' => 'Macedonia',
						'Madagascar' => 'Madagascar',
						'Malawi' => 'Malawi',
						'Malaysia' => 'Malaysia',
						'Maldives' => 'Maldives',
						'Mali' => 'Mali',
						'Malta' => 'Malta',
						'Marshall' => 'Marshall',
						'Mauritania' => 'Mauritania',
						'Mauritius' => 'Mauritius',
						'Mexico' => 'Mexico',
						'Micronesia' => 'Micronesia',
						'Moldova' => 'Moldova',
						'Monaco' => 'Monaco',
						'Mongolia' => 'Mongolia',
						'Montenegro' => 'Montenegro',
						'Morocco' => 'Morocco',
						'Mozambique' => 'Mozambique',
						'Myanmar' => 'Myanmar',
						'Namibia' => 'Namibia',
						'Nauru' => 'Nauru',
						'Nepal' => 'Nepal',
						'Netherlands' => 'Netherlands',
						'New Zealand' => 'New Zealand',
						'Nicaragua' => 'Nicaragua',
						'Niger' => 'Niger',
						'Nigeria' => 'Nigeria',
						'Norway' => 'Norway',
						'Oman' => 'Oman',
						'Pakistan' => 'Pakistan',
						'Palau' => 'Palau',
						'Panama' => 'Panama',
						'Papua' => 'Papua',
						'Paraguay' => 'Paraguay',
						'Peru' => 'Peru',
						'Philippines' => 'Philippines',
						'Poland' => 'Poland',
						'Portugal' => 'Portugal',
						'Qatar' => 'Qatar',
						'Romania' => 'Romania',
						'Russia' => 'Russia',
						'Rwanda' => 'Rwanda',
						'Samoa' => 'Samoa',
						'San Marino' => 'San Marino',
						'Sao Tome' => 'Sao Tome',
						'Saudi Arabia' => 'Saudi Arabia',
						'Scotland' => 'Scotland',
						'Scottish' => 'Scottish',
						'Senegal' => 'Senegal',
						'Serbia' => 'Serbia',
						'Seychelles' => 'Seychelles',
						'Sierra Leone' => 'Sierra Leone',
						'Singapore' => 'Singapore',
						'Slovakia' => 'Slovakia',
						'Slovenia' => 'Slovenia',
						'Solomon' => 'Solomon',
						'Somalia' => 'Somalia',
						'South Africa' => 'South Africa',
						'South Sudan' => 'South Sudan',
						'Spain' => 'Spain',
						'Sri Lanka' => 'Sri Lanka',
						'St Kitts' => 'St Kitts',
						'St Lucia' => 'St Lucia',
						'Sudan' => 'Sudan',
						'Suriname' => 'Suriname',
						'Swaziland' => 'Swaziland',
						'Sweden' => 'Sweden',
						'Switzerland' => 'Switzerland',
						'Syria' => 'Syria',
						'Taiwan' => 'Taiwan',
						'Tajikistan' => 'Tajikistan',
						'Tanzania' => 'Tanzania',
						'Thailand' => 'Thailand',
						'Tobago' => 'Tobago',
						'Togo' => 'Togo',
						'Tonga' => 'Tonga',
						'Trinidad' => 'Trinidad',
						'Tunisia' => 'Tunisia',
						'Turkey' => 'Turkey',
						'Turkmenistan' => 'Turkmenistan',
						'Tuvalu' => 'Tuvalu',
						'Uganda' => 'Uganda',
						'Ukraine' => 'Ukraine',
						'United Kingdom' => 'United Kingdom',
						'United States' => 'United States',
						'Uruguay' => 'Uruguay',
						'USA' => 'USA',
						'Uzbekistan' => 'Uzbekistan',
						'Vanuatu' => 'Vanuatu',
						'Vatican' => 'Vatican',
						'Venezuela' => 'Venezuela',
						'Vietnam' => 'Vietnam',
						'Wales' => 'Wales',
						'Welsh' => 'Welsh',
						'Yemen' => 'Yemen',
						'Zambia' => 'Zambia',
						'Zimbabwe' => 'Zimbabwe',
					),
					'default_value' => array(
					),
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 1,
					'ajax' => 0,
					'return_format' => 'value',
					'placeholder' => '',
				),
				array(
					'key' => 'field_5d09e5f9a08fa',
					'label' => 'Extindere',
					'name' => 'extindere',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'locala' => 'locala',
						'regionala' => 'regionala',
						'multinationala' => 'multinationala',
					),
					'default_value' => array(
					),
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'return_format' => 'value',
					'ajax' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_5d09e5f9a093b',
					'label' => 'Localizare in Romania',
					'name' => 'localizare',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'Alba' => 'Alba',
						'Arad' => 'Arad',
						'Arges' => 'Arges',
						'Bacau' => 'Bacau',
						'Bihor' => 'Bihor',
						'Bistrita-Nasaud' => 'Bistrita-Nasaud',
						'Botosani' => 'Botosani',
						'Brasov' => 'Brasov',
						'Braila' => 'Braila',
						'Bucuresti' => 'Bucuresti',
						'Buzau' => 'Buzau',
						'Caras-Severin' => 'Caras-Severin',
						'Cluj' => 'Cluj',
						'Constanta' => 'Constanta',
						'Covasna' => 'Covasna',
						'Dimbovita' => 'Dimbovita',
						'Dolj' => 'Dolj',
						'Galati' => 'Galati',
						'Gorj' => 'Gorj',
						'Harghita' => 'Harghita',
						'Hunedoara' => 'Hunedoara',
						'Ialomita' => 'Ialomita',
						'Iasi' => 'Iasi',
						'Ilfov' => 'Ilfov',
						'Maramures' => 'Maramures',
						'Mehedinti' => 'Mehedinti',
						'Mures' => 'Mures',
						'Neamt' => 'Neamt',
						'Olt' => 'Olt',
						'Prahova' => 'Prahova',
						'Satu_Mare' => 'Satu_Mare',
						'Salaj' => 'Salaj',
						'Sibiu' => 'Sibiu',
						'Suceava' => 'Suceava',
						'Teleorman' => 'Teleorman',
						'Timis' => 'Timis',
						'Tulcea' => 'Tulcea',
						'Vaslui' => 'Vaslui',
						'Vilcea' => 'Vilcea',
						'Vrancea' => 'Vrancea',
						'Calarasi' => 'Calarasi',
						'Giurgiu' => 'Giurgiu',
					),
					'default_value' => array(
					),
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 1,
					'ajax' => 0,
					'return_format' => 'value',
					'placeholder' => '',
				),
				array(
					'key' => 'field_5d09e5f9a097d',
					'label' => 'Head Office',
					'name' => 'head_office',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => 'Head Office',
					'prepend' => '',
					'append' => '',
					'maxlength' => 40,
				),
				array(
					'key' => 'field_5d09e5f9a09be',
					'label' => 'Cifra de afaceri in RO',
					'name' => 'cifra_de_afaceri',
					'type' => 'number',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => 'Cifra de afaceri in RO (euro)',
					'prepend' => '',
					'append' => '',
					'min' => '',
					'max' => '',
					'step' => '',
				),
				array(
					'key' => 'field_5d09e5f9a0a00',
					'label' => 'Numar de angajati',
					'name' => 'nr_de_angajati',
					'type' => 'number',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => 'Numar de angajati',
					'prepend' => '',
					'append' => '',
					'min' => '',
					'max' => '',
					'step' => '',
				),
			),
		),
		array(
			'key' => 'field_5d4aa946caeb9',
			'label' => 'Date visibile',
			'name' => 'date_visibile',
			'type' => 'checkbox',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'choices' => array(
				'nume' => 'Nume',
				'nume-alternativ' => 'Nume alternativ',
				'origine' => 'Orgine',
				'extindere' => 'Extindere',
				'localizare-ro' => 'Localizare in RO',
				'head-office' => 'Head Office',
				'cifra_afaceri' => 'Cifra de afaceri',
				'nr-angajati' => 'Numar angajati',
				'descriere' => 'Descriere companie',
				'domeniu-sintetic' => 'Descriere domeniu (sintetic)',
				'domeniu-larg' => 'Descriere domeniu (pe larg)',
				'note-companie' => 'Note companie',
			),
			'allow_custom' => 0,
			'default_value' => array(
			),
			'layout' => 'horizontal',
			'toggle' => 1,
			'return_format' => 'value',
			'acfe_validate' => '',
			'acfe_update' => '',
			'save_custom' => 0,
		),
		array(
			'key' => 'field_5d09e5f99b22d',
			'label' => 'Descriere companie',
			'name' => 'descriere_companie',
			'type' => 'wysiwyg',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'default_value' => '',
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 0,
			'delay' => 0,
			'acfe_validate' => false,
			'acfe_update' => false,
		),
		array(
			'key' => 'field_5d09ed3d884ec',
			'label' => 'Descriere domeniu	de activitate (sintetic)',
			'name' => 'descriere_domeniu_sintetic',
			'type' => 'wysiwyg',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'default_value' => '',
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 0,
			'delay' => 0,
			'acfe_validate' => false,
			'acfe_update' => false,
		),
		array(
			'key' => 'field_5d09ed6e24628',
			'label' => 'Descriere domeniu	de activitate (pe larg)',
			'name' => 'descriere_domeniu_larg',
			'type' => 'wysiwyg',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'default_value' => '',
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 0,
			'delay' => 0,
			'acfe_validate' => false,
			'acfe_update' => false,
		),
		array(
			'key' => 'field_5d09e5f99b373',
			'label' => 'Note si comentarii libere',
			'name' => 'note_comentarii',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => 3,
			'new_lines' => 'br',
			'acfe_validate' => false,
			'acfe_update' => false,
		),
		array(
			'key' => 'field_5d09e5f99b26e',
			'label' => 'Link-uri',
			'name' => 'link-uri_companie',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'collapsed' => '',
			'min' => 0,
			'max' => 0,
			'layout' => 'table',
			'button_label' => 'Adauga link nou',
			'sub_fields' => array(
				array(
					'key' => 'field_5d09e5f9edc83',
					'label' => 'Link',
					'name' => 'link',
					'type' => 'url',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '70',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => 'ex	https://www.facebook.com/managero',
				),
				array(
					'key' => 'field_5d09e5f9edcd4',
					'label' => 'Titlu',
					'name' => 'titlu',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '31',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => 'ex facebook',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
			),
		),
		array(
			'key' => 'field_5d09e5f99b3b4',
			'label' => 'Imagine	profil',
			'name' => 'imagine_profil_companie',
			'type' => 'image_aspect_ratio_crop',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'aspect_ratio_width' => 240,
			'aspect_ratio_height' => 120,
			'return_format' => 'id',
			'preview_size' => 'medium',
			'library' => 'uploadedTo',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
			'acfe_validate' => false,
			'acfe_update' => false,
		),
		array(
			'key' => 'field_5d35aa533fae5',
			'label' => 'Date profil',
			'name' => 'data_template',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_5d35a47a35468',
					'label' => 'Nume profil',
					'name' => 'nume_template',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'acfe_validate' => '',
					'acfe_update' => '',
				),
				array(
					'key' => 'field_5d35a9dc3b621',
					'label' => 'Descriere profil',
					'name' => 'descriere_template',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'default_value' => '',
					'placeholder' => '',
					'maxlength' => '',
					'rows' => '',
					'new_lines' => '',
					'acfe_validate' => '',
					'acfe_update' => '',
				),
			),
		),
		array(
			'key' => 'field_5d45bf0621d79',
			'label' => 'Salveaza',
			'name' => 'salveaza2',
			'type' => 'button',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'button_value' => 'Salveaza',
			'button_attributes' => array(
				'button_type' => 'button',
				'button_class' => 'btn-standard',
				'button_id' => 'salveaza_profil_job',
			),
			'button_wrapper' => array(
				'button_before' => '',
				'button_after' => '',
			),
			'acfe_validate' => '',
			'acfe_update' => '',
		),
		array(
			'key' => 'field_5d45b4b5fb22e',
			'label' => 'Salveaza ca',
			'name' => 'salveaza_ca',
			'type' => 'button',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'button_value' => 'Salveaza ca',
			'button_attributes' => array(
				'button_type' => 'button',
				'button_class' => 'btn-standard',
				'button_id' => 'salveaza_ca_job_profil',
			),
			'button_wrapper' => array(
				'button_before' => '',
				'button_after' => '',
			),
			'acfe_validate' => '',
			'acfe_update' => '',
		),
		array(
			'key' => 'field_5d45b4f0b5dba',
			'label' => 'Delete template',
			'name' => 'delete_template',
			'type' => 'button',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'button_value' => 'Delete',
			'button_attributes' => array(
				'button_type' => 'button',
				'button_class' => '',
				'button_id' => 'delete_template',
			),
			'button_wrapper' => array(
				'button_before' => '',
				'button_after' => '',
			),
			'acfe_validate' => '',
			'acfe_update' => '',
		),
		array(
			'key' => 'field_5d45b51d0341a',
			'label' => 'Salveaza ca un nou profil',
			'name' => 'salveaza_ca_un_nou_template',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => 'wrap-salveaza-ca',
			),
			'acfe_permissions' => '',
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_5d45b53f0341b',
					'label' => 'Nume profil',
					'name' => 'nume_template_as',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'acfe_validate' => '',
					'acfe_update' => '',
				),
				array(
					'key' => 'field_5d45b5660341c',
					'label' => 'Descriere profil',
					'name' => 'descriere_template_as',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'default_value' => '',
					'placeholder' => '',
					'maxlength' => '',
					'rows' => 2,
					'new_lines' => '',
					'acfe_validate' => '',
					'acfe_update' => '',
				),
				array(
					'key' => 'field_5d45b5740341d',
					'label' => 'OK',
					'name' => 'ok',
					'type' => 'button',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'button_value' => 'Ok',
					'button_attributes' => array(
						'button_type' => 'button',
						'button_class' => 'btn-standard',
						'button_id' => 'ok_save_as',
					),
					'button_wrapper' => array(
						'button_before' => '',
						'button_after' => '',
					),
					'acfe_validate' => '',
					'acfe_update' => '',
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'employer',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
	'acfe_display_title' => '',
	'acfe_autosync' => array(
		0 => 'php',
	),
	'acfe_permissions' => '',
	'acfe_note' => '',
	'acfe_meta' => '',
	'modified' => 1565545816,
));

endif;