<?php 

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_profil_job',
	'title' => 'Profil Job',
	'fields' => array(
		array(
			'key' => 'field_5d41677f4ce30',
			'label' => 'Nume post',
			'name' => 'post_job',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'acfe_validate' => '',
			'acfe_update' => '',
		),
		array(
			'key' => 'field_5d4167914ce31',
			'label' => 'Pozitia ierarhica',
			'name' => 'pozitia_ierarhica',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_5d4167a94ce32',
					'label' => 'Nivel Ierarhic',
					'name' => 'nivelul_ierarhic',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'choices' => array(
						'ceo' => 'ceo',
						'ceo -1' => 'ceo -1',
						'ceo -2' => 'ceo -2',
						'middle management' => 'middle management',
						'board executive' => 'board executive',
						'board non-executive' => 'board non-executive',
						'alt nivel' => 'alt nivel',
					),
					'default_value' => array(
					),
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'return_format' => 'value',
					'acfe_validate' => '',
					'acfe_update' => '',
					'ajax' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_5d4167d14ce33',
					'label' => 'Cui este subordonat',
					'name' => 'cui_este_subordonat',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'acfe_validate' => '',
					'acfe_update' => '',
				),
				array(
					'key' => 'field_5d4167ff4ce34',
					'label' => 'Cati subordonati are in total',
					'name' => 'cati_subordonati_are_in_total',
					'type' => 'number',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'min' => '',
					'max' => '',
					'step' => '',
					'acfe_validate' => '',
					'acfe_update' => '',
				),
			),
		),
		array(
			'key' => 'field_5d4168184ce35',
			'label' => 'Domeniu',
			'name' => 'domeniu',
			'type' => 'taxonomy',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'taxonomy' => 'sector',
			'field_type' => 'checkbox',
			'add_term' => 0,
			'save_terms' => 1,
			'load_terms' => 0,
			'return_format' => 'object',
			'acfe_bidirectional' => array(
				'acfe_bidirectional_enabled' => '0',
			),
			'acfe_validate' => '',
			'acfe_update' => '',
			'multiple' => 0,
			'allow_null' => 0,
		),
		array(
			'key' => 'field_5d41684a4ce36',
			'label' => 'Locatia jobului',
			'name' => 'locatia_jobului',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'choices' => array(
				'Alba' => 'Alba',
				'Arad' => 'Arad',
				'Arges' => 'Arges',
				'Bacau' => 'Bacau',
				'Bihor' => 'Bihor',
				'Bistrita-Nasaud' => 'Bistrita-Nasaud',
				'Botosani' => 'Botosani',
				'Braila' => 'Braila',
				'Brasov' => 'Brasov',
				'Bucuresti' => 'Bucuresti',
				'Buzau' => 'Buzau',
				'Calarasi' => 'Calarasi',
				'Caras	Severin' => 'Caras	Severin',
				'Caras-Severin' => 'Caras-Severin',
				'Cluj' => 'Cluj',
				'Constanta' => 'Constanta',
				'Covasna' => 'Covasna',
				'Dambovita' => 'Dambovita',
				'Dolj' => 'Dolj',
				'Galati' => 'Galati',
				'Giurgiu' => 'Giurgiu',
				'Gorj' => 'Gorj',
				'Harghita' => 'Harghita',
				'Hargita' => 'Hargita',
				'Hunedoara' => 'Hunedoara',
				'Ialomita' => 'Ialomita',
				'Iasi' => 'Iasi',
				'Ilfov' => 'Ilfov',
				'Maramures' => 'Maramures',
				'Mehedinti' => 'Mehedinti',
				'Mures' => 'Mures',
				'Neamt' => 'Neamt',
				'Olt' => 'Olt',
				'Prahova' => 'Prahova',
				'Salaj' => 'Salaj',
				'Satu	Mare' => 'Satu	Mare',
				'Sibiu' => 'Sibiu',
				'Suceava' => 'Suceava',
				'Teleorman' => 'Teleorman',
				'Timis' => 'Timis',
				'Tulcea' => 'Tulcea',
				'Valcea' => 'Valcea',
				'Vaslui' => 'Vaslui',
				'Vrancea' => 'Vrancea',
			),
			'default_value' => array(
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 1,
			'ajax' => 0,
			'return_format' => 'value',
			'acfe_validate' => '',
			'acfe_update' => '',
			'placeholder' => '',
		),
		array(
			'key' => 'field_5d41686c4ce37',
			'label' => 'Descrierea sintetica a jobului',
			'name' => 'descrierea_sintetica_a_jobului',
			'type' => 'wysiwyg',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'default_value' => '',
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 0,
			'delay' => 0,
			'acfe_validate' => '',
			'acfe_update' => '',
		),
		array(
			'key' => 'field_5d41687a4ce38',
			'label' => 'Cerinte job',
			'name' => 'cerinte_job',
			'type' => 'wysiwyg',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'default_value' => '',
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 0,
			'delay' => 0,
			'acfe_validate' => '',
			'acfe_update' => '',
		),
		array(
			'key' => 'field_5d41688a4ce39',
			'label' => 'Oferta',
			'name' => 'oferta',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_5d4168c24ce3a',
					'label' => 'Salariu',
					'name' => 'salariu',
					'type' => 'number',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'min' => '',
					'max' => '',
					'step' => '',
					'acfe_validate' => '',
					'acfe_update' => '',
				),
				array(
					'key' => 'field_5d4168d04ce3b',
					'label' => 'Descriere sintetica a ofertei',
					'name' => 'descriere_sintetica_a_ofertei',
					'type' => 'wysiwyg',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'default_value' => '',
					'tabs' => 'all',
					'toolbar' => 'full',
					'media_upload' => 0,
					'delay' => 0,
					'acfe_validate' => '',
					'acfe_update' => '',
				),
			),
		),
		array(
			'key' => 'field_5d4168ec4ce3c',
			'label' => 'Cum sa aplice',
			'name' => 'cum_sa_aplice',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_5d41690c4ce3d',
					'label' => 'Mod aplicare',
					'name' => 'mod_aplicare',
					'type' => 'checkbox',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'choices' => array(
						'Managero' => 'Managero',
						'E-mail' => 'E-mail',
					),
					'allow_custom' => 0,
					'default_value' => array(
					),
					'layout' => 'horizontal',
					'toggle' => 0,
					'return_format' => 'value',
					'acfe_validate' => '',
					'acfe_update' => '',
					'save_custom' => 0,
				),
				array(
					'key' => 'field_5d4aab48406bb',
					'label' => 'Instructiuni aplicare pe email',
					'name' => 'instructiuni_aplicare',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5d41690c4ce3d',
								'operator' => '==',
								'value' => 'E-mail',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'default_value' => '',
					'placeholder' => '',
					'maxlength' => '',
					'rows' => 3,
					'new_lines' => '',
					'acfe_validate' => '',
					'acfe_update' => '',
				),
			),
		),
		array(
			'key' => 'field_5d4169372287b',
			'label' => 'Filtre candidati',
			'name' => 'filtre_candidati',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_5d4169432287c',
					'label' => 'Varsta',
					'name' => 'varsta',
					'type' => 'number',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'min' => '',
					'max' => '',
					'step' => '',
					'acfe_validate' => '',
					'acfe_update' => '',
				),
				array(
					'key' => 'field_5d4169512287d',
					'label' => 'Sex',
					'name' => 'sex',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'choices' => array(
						'masculin' => 'Masculin',
						'feminin' => 'Feminin',
						'nespecificat' => 'Nespecificat',
					),
					'default_value' => array(
					),
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'return_format' => 'value',
					'acfe_validate' => '',
					'acfe_update' => '',
					'ajax' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_5d4169682287e',
					'label' => 'Salariu minim',
					'name' => 'salariu_minim',
					'type' => 'number',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'min' => '',
					'max' => '',
					'step' => '',
					'acfe_validate' => '',
					'acfe_update' => '',
				),
			),
		),
		array(
			'key' => 'field_5d416a5e29f85',
			'label' => 'Fisiere atasate',
			'name' => 'fisiere_atasate',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'collapsed' => '',
			'min' => 0,
			'max' => 0,
			'layout' => 'table',
			'button_label' => '',
			'sub_fields' => array(
				array(
					'key' => 'field_5d416a7129f86',
					'label' => 'Fisier',
					'name' => 'fisier',
					'type' => 'file',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'return_format' => 'url',
					'library' => 'all',
					'min_size' => '',
					'max_size' => '',
					'mime_types' => '',
					'acfe_validate' => '',
					'acfe_update' => '',
				),
				array(
					'key' => 'field_5d416a8729f87',
					'label' => 'Denumire',
					'name' => 'denumire',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'acfe_validate' => '',
					'acfe_update' => '',
				),
			),
		),
		array(
			'key' => 'field_5d4169c4c0cac',
			'label' => 'Galerie',
			'name' => 'galerie',
			'type' => 'gallery',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'return_format' => 'array',
			'preview_size' => 'medium',
			'insert' => 'append',
			'library' => 'all',
			'min' => '',
			'max' => '',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
			'acfe_validate' => '',
			'acfe_update' => '',
		),
		array(
			'key' => 'field_5d4169eec0cad',
			'label' => 'Comentarii job',
			'name' => 'comentarii_job',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => '',
			'acfe_validate' => '',
			'acfe_update' => '',
		),
		array(
			'key' => 'field_5d4169fbc0cae',
			'label' => 'Imagine Cover',
			'name' => 'imagine_cover_2',
			'type' => 'image_aspect_ratio_crop',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'aspect_ratio_width' => 1100,
			'aspect_ratio_height' => 300,
			'return_format' => 'id',
			'preview_size' => 'large',
			'library' => 'all',
			'min_width' => 1100,
			'min_height' => 300,
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
			'acfe_validate' => '',
			'acfe_update' => '',
		),
		array(
			'key' => 'field_5d416a2cc0caf',
			'label' => 'Data template',
			'name' => 'data_template',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => 'wrap-salveaza-new',
			),
			'acfe_permissions' => '',
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_5d416acac61e8',
					'label' => 'Nume template',
					'name' => 'nume_template',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'acfe_validate' => '',
					'acfe_update' => '',
				),
				array(
					'key' => 'field_5d416ad5c61e9',
					'label' => 'Descriere template',
					'name' => 'descriere_template',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'default_value' => '',
					'placeholder' => '',
					'maxlength' => '',
					'rows' => 2,
					'new_lines' => '',
					'acfe_validate' => '',
					'acfe_update' => '',
				),
			),
		),
		array(
			'key' => 'field_5d416ae5c61ea',
			'label' => 'Salveaza',
			'name' => 'salveaza',
			'type' => 'button',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'button_value' => 'Salveaza',
			'button_attributes' => array(
				'button_type' => 'button',
				'button_class' => '',
				'button_id' => 'salveaza_profil_job',
			),
			'button_wrapper' => array(
				'button_before' => '',
				'button_after' => '',
			),
			'acfe_validate' => '',
			'acfe_update' => '',
		),
		array(
			'key' => 'field_5d416b0cc61eb',
			'label' => 'Salveaza ca',
			'name' => 'salveaza_ca',
			'type' => 'button',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'button_value' => 'Salveaza ca',
			'button_attributes' => array(
				'button_type' => 'button',
				'button_class' => '',
				'button_id' => 'salveaza_ca_job_profil',
			),
			'button_wrapper' => array(
				'button_before' => '',
				'button_after' => '',
			),
			'acfe_validate' => '',
			'acfe_update' => '',
		),
		array(
			'key' => 'field_5d432f948858a',
			'label' => 'Delete template',
			'name' => 'delete_template',
			'type' => 'button',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'button_value' => 'Delete',
			'button_attributes' => array(
				'button_type' => 'button',
				'button_class' => '',
				'button_id' => 'delete_template',
			),
			'button_wrapper' => array(
				'button_before' => '',
				'button_after' => '',
			),
			'acfe_validate' => '',
			'acfe_update' => '',
		),
		array(
			'key' => 'field_5d432fe08858b',
			'label' => 'Salveaza ca un nou template',
			'name' => 'salveaza_ca_un_nou_template',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => 'wrap-salveaza-ca',
			),
			'acfe_permissions' => '',
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_5d432fee8858c',
					'label' => 'Nume template',
					'name' => 'nume_template_as',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'acfe_validate' => '',
					'acfe_update' => '',
				),
				array(
					'key' => 'field_5d432ff58858d',
					'label' => 'Descriere template',
					'name' => 'descriere_template_as',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'default_value' => '',
					'placeholder' => '',
					'maxlength' => '',
					'rows' => 2,
					'new_lines' => '',
					'acfe_validate' => '',
					'acfe_update' => '',
				),
				array(
					'key' => 'field_5d43301e8858e',
					'label' => 'ok',
					'name' => 'ok',
					'type' => 'button',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'button_value' => 'OK',
					'button_attributes' => array(
						'button_type' => 'button',
						'button_class' => '',
						'button_id' => 'ok_save_as',
					),
					'button_wrapper' => array(
						'button_before' => '',
						'button_after' => '',
					),
					'acfe_validate' => '',
					'acfe_update' => '',
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'post',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'left',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
	'acfe_display_title' => '',
	'acfe_autosync' => array(
		0 => 'php',
	),
	'acfe_permissions' => '',
	'acfe_note' => '',
	'acfe_meta' => '',
	'modified' => 1565174679,
));

endif;