<?php 

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_job_complet',
	'title' => 'Anunt',
	'fields' => array(
		array(
			'key' => 'field_5d38458292fdb',
			'label' => 'Companie',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5d4bf6f20de13',
			'label' => 'Profil companie',
			'name' => 'profil_companie',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '100',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_5d4bf7380de14',
					'label' => 'Alege profil companie',
					'name' => 'alege_profil_companie',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'choices' => array(
					),
					'default_value' => array(
					),
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'return_format' => 'value',
					'acfe_validate' => '',
					'acfe_update' => '',
					'ajax' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_5d4bf9782eb1d',
					'label' => 'Aplica profil companie',
					'name' => 'aplica_profil_companie',
					'type' => 'button',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'button_value' => 'Aplica profil companie',
					'button_attributes' => array(
						'button_type' => 'button',
						'button_class' => '',
						'button_id' => 'aplica_companie',
					),
					'button_wrapper' => array(
						'button_before' => '',
						'button_after' => '',
					),
					'acfe_validate' => '',
					'acfe_update' => '',
				),
			),
		),
		array(
			'key' => 'field_5d0bfb256cebc',
			'label' => 'Date visibile',
			'name' => 'date_visibile',
			'type' => 'checkbox',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'choices' => array(
				'nume' => 'Nume',
				'nume-alternativ' => 'Nume alternativ',
				'origine' => 'Orgine',
				'extindere' => 'Extindere',
				'localizare-ro' => 'Localizare in RO',
				'head-office' => 'Head Office',
				'cifra_afaceri' => 'Cifra de afaceri',
				'nr-angajati' => 'Numar angajati',
				'descriere' => 'Descriere companie',
				'domeniu-sintetic' => 'Descriere domeniu (sintetic)',
				'domeniu-larg' => 'Descriere domeniu (pe larg)',
				'note-companie' => 'Note companie',
			),
			'allow_custom' => 0,
			'default_value' => array(
			),
			'layout' => 'horizontal',
			'toggle' => 1,
			'return_format' => 'value',
			'acfe_validate' => '',
			'acfe_update' => '',
			'save_custom' => 0,
		),
		array(
			'key' => 'field_5d2ccd823cd80',
			'label' => 'Date companie',
			'name' => 'date_companie_2',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => 'plm',
			),
			'acfe_permissions' => '',
			'layout' => 'row',
			'sub_fields' => array(
				array(
					'key' => 'field_5d2ccd9f3cd81',
					'label' => 'Nume',
					'name' => 'nume_companie',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5d0bfb256cebc',
								'operator' => '==',
								'value' => 'nume',
							),
						),
					),
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5d2ccdd53cd82',
					'label' => 'Nume alternativ',
					'name' => 'nume_alternativ',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5d0bfb256cebc',
								'operator' => '==',
								'value' => 'nume-alternativ',
							),
						),
					),
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5d2ccddd3cd83',
					'label' => 'Origine',
					'name' => 'origine',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5d0bfb256cebc',
								'operator' => '==',
								'value' => 'origine',
							),
						),
					),
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'Abhazia' => 'Abhazia',
						'Afghanistan' => 'Afghanistan',
						'Africa de Sud' => 'Africa de Sud',
						'Albania' => 'Albania',
						'Algeria' => 'Algeria',
						'Andorra' => 'Andorra',
						'Angola' => 'Angola',
						'Antigua și Barbuda' => 'Antigua și Barbuda',
						'Arabia Saudită' => 'Arabia Saudită',
						'Argentina' => 'Argentina',
						'Armenia' => 'Armenia',
						'Australia' => 'Australia',
						'Austria' => 'Austria',
						'Azerbaijan' => 'Azerbaijan',
						'Bahamas' => 'Bahamas',
						'Bahrain' => 'Bahrain',
						'Bangladesh' => 'Bangladesh',
						'Barbados' => 'Barbados',
						'Belarus' => 'Belarus',
						'Belgia' => 'Belgia',
						'Belize' => 'Belize',
						'Benin' => 'Benin',
						'Bhutan' => 'Bhutan',
						'Bolivia' => 'Bolivia',
						'Bosnia și Herțegovina' => 'Bosnia și Herțegovina',
						'Botswana' => 'Botswana',
						'Brazilia' => 'Brazilia',
						'Brunei' => 'Brunei',
						'Bulgaria' => 'Bulgaria',
						'Burkina Faso' => 'Burkina Faso',
						'Burundi' => 'Burundi',
						'Cambodgia' => 'Cambodgia',
						'Camerun' => 'Camerun',
						'Canada' => 'Canada',
						'Capul Verde' => 'Capul Verde',
						'Cehia' => 'Cehia',
						'Chile' => 'Chile',
						'Ciad' => 'Ciad',
						'Cipru' => 'Cipru',
						'Columbia' => 'Columbia',
						'Comore' => 'Comore',
						'Congo' => 'Congo',
						'Coreea de Nord' => 'Coreea de Nord',
						'Coreea de Sud' => 'Coreea de Sud',
						'Costa Rica' => 'Costa Rica',
						'Côte d\'Ivoire' => 'Côte d\'Ivoire',
						'Croația' => 'Croația',
						'Cuba' => 'Cuba',
						'Curaçao' => 'Curaçao',
						'Danemarca' => 'Danemarca',
						'Djibouti' => 'Djibouti',
						'Dominica' => 'Dominica',
						'Ecuador' => 'Ecuador',
						'Egipt' => 'Egipt',
						'El Salvador' => 'El Salvador',
						'Elveția' => 'Elveția',
						'Emiratele Arabe Unite' => 'Emiratele Arabe Unite',
						'Eritreea' => 'Eritreea',
						'Estonia' => 'Estonia',
						'Etiopia' => 'Etiopia',
						'Fiji' => 'Fiji',
						'Filipine' => 'Filipine',
						'Finlanda' => 'Finlanda',
						'Ciprul de Nord' => 'Ciprul de Nord',
						'Franța' => 'Franța',
						'Gabon' => 'Gabon',
						'Gambia' => 'Gambia',
						'Georgia' => 'Georgia',
						'Germania' => 'Germania',
						'Ghana' => 'Ghana',
						'Grecia' => 'Grecia',
						'Grenada' => 'Grenada',
						'Guam' => 'Guam',
						'Guatemala' => 'Guatemala',
						'Guinea' => 'Guinea',
						'Guinea-Bissau' => 'Guinea-Bissau',
						'Guineea Ecuatorială' => 'Guineea Ecuatorială',
						'Guyana' => 'Guyana',
						'Haiti' => 'Haiti',
						'Honduras' => 'Honduras',
						'India' => 'India',
						'Indonezia' => 'Indonezia',
						'Insulele Marshall' => 'Insulele Marshall',
						'Insulele Solomon' => 'Insulele Solomon',
						'Iordania' => 'Iordania',
						'Irak' => 'Irak',
						'Iran' => 'Iran',
						'Irlanda' => 'Irlanda',
						'Islanda' => 'Islanda',
						'Israel' => 'Israel',
						'Italia' => 'Italia',
						'Jamaica' => 'Jamaica',
						'Japonia' => 'Japonia',
						'Kazakhstan' => 'Kazakhstan',
						'Kenya' => 'Kenya',
						'Kîrgîzstan' => 'Kîrgîzstan',
						'Kiribati' => 'Kiribati',
						'Kosovo' => 'Kosovo',
						'Kuwait' => 'Kuwait',
						'Laos' => 'Laos',
						'Lesotho' => 'Lesotho',
						'Letonia' => 'Letonia',
						'Liban' => 'Liban',
						'Liberia' => 'Liberia',
						'Libia' => 'Libia',
						'Liechtenstein' => 'Liechtenstein',
						'Lituania' => 'Lituania',
						'Luxemburg' => 'Luxemburg',
						'Macedonia de Nord' => 'Macedonia de Nord',
						'Madagascar' => 'Madagascar',
						'Malawi' => 'Malawi',
						'Malaysia' => 'Malaysia',
						'Maldive' => 'Maldive',
						'Mali' => 'Mali',
						'Malta' => 'Malta',
						'Maroc' => 'Maroc',
						'Mauritania' => 'Mauritania',
						'Mauritius' => 'Mauritius',
						'Mexic' => 'Mexic',
						'Moldova' => 'Moldova',
						'Monaco' => 'Monaco',
						'Mongolia' => 'Mongolia',
						'Mozambic' => 'Mozambic',
						'Muntenegru' => 'Muntenegru',
						'Myanmar' => 'Myanmar',
						'Namibia' => 'Namibia',
						'Nauru' => 'Nauru',
						'Nepal' => 'Nepal',
						'Nicaragua' => 'Nicaragua',
						'Niger' => 'Niger',
						'Nigeria' => 'Nigeria',
						'Norvegia' => 'Norvegia',
						'Noua Caledonie' => 'Noua Caledonie',
						'Noua Zeelandă' => 'Noua Zeelandă',
						'Oman' => 'Oman',
						'Pakistan' => 'Pakistan',
						'Palau' => 'Palau',
						'Palestina' => 'Palestina',
						'Panama' => 'Panama',
						'Papua Noua Guinee' => 'Papua Noua Guinee',
						'Paraguay' => 'Paraguay',
						'Peru' => 'Peru',
						'Polinezia Franceză' => 'Polinezia Franceză',
						'Polonia' => 'Polonia',
						'Portugalia' => 'Portugalia',
						'Qatar' => 'Qatar',
						'RD Congo' => 'RD Congo',
						'Regatul Unit' => 'Regatul Unit',
						'Republica Centrafricană' => 'Republica Centrafricană',
						'Republica China (Taiwan)' => 'Republica China (Taiwan)',
						'Republica Dominicană' => 'Republica Dominicană',
						'Republica Populară Chineză' => 'Republica Populară Chineză',
						'România' => 'România',
						'Rusia' => 'Rusia',
						'Rwanda' => 'Rwanda',
						'Sahara Occidentală' => 'Sahara Occidentală',
						'Samoa' => 'Samoa',
						'San Marino' => 'San Marino',
						'São Tomé și Príncipe' => 'São Tomé și Príncipe',
						'Senegal' => 'Senegal',
						'Serbia' => 'Serbia',
						'Seychelles' => 'Seychelles',
						'Sfânta Lucia' => 'Sfânta Lucia',
						'Sfântul Kitts și Nevis' => 'Sfântul Kitts și Nevis',
						'Sfântul Vicențiu și Grenadine' => 'Sfântul Vicențiu și Grenadine',
						'Sierra Leone' => 'Sierra Leone',
						'Singapore' => 'Singapore',
						'Siria' => 'Siria',
						'Slovacia' => 'Slovacia',
						'Slovenia' => 'Slovenia',
						'Somalia' => 'Somalia',
						'Spania' => 'Spania',
						'Sri Lanka' => 'Sri Lanka',
						'Statele Federate ale Microneziei' => 'Statele Federate ale Microneziei',
						'SUA' => 'SUA',
						'Sudan' => 'Sudan',
						'Sudanul de Sud' => 'Sudanul de Sud',
						'Suedia' => 'Suedia',
						'Surinam' => 'Surinam',
						'Swaziland' => 'Swaziland',
						'Tajikistan' => 'Tajikistan',
						'Tanzania' => 'Tanzania',
						'Thailanda' => 'Thailanda',
						'Timorul de Est' => 'Timorul de Est',
						'Togo' => 'Togo',
						'Tonga' => 'Tonga',
						'Transnistria' => 'Transnistria',
						'Trinidad-Tobago' => 'Trinidad-Tobago',
						'Țările de Jos' => 'Țările de Jos',
						'Tunisia' => 'Tunisia',
						'Turcia' => 'Turcia',
						'Turkmenistan' => 'Turkmenistan',
						'Tuvalu' => 'Tuvalu',
						'Ucraina' => 'Ucraina',
						'Uganda' => 'Uganda',
						'Ungaria' => 'Ungaria',
						'Uruguay' => 'Uruguay',
						'Uzbekistan' => 'Uzbekistan',
						'Vanuatu' => 'Vanuatu',
						'Vatican' => 'Vatican',
						'Venezuela' => 'Venezuela',
						'Vietnam' => 'Vietnam',
						'Yemen' => 'Yemen',
						'Zambia' => 'Zambia',
						'Zimbabwe' => 'Zimbabwe',
					),
					'default_value' => array(
					),
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 1,
					'ajax' => 0,
					'return_format' => 'value',
					'placeholder' => '',
				),
				array(
					'key' => 'field_5d2cd0f8f5198',
					'label' => 'Localizare in Romania',
					'name' => 'localizare_in_romania',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5d0bfb256cebc',
								'operator' => '==',
								'value' => 'localizare-ro',
							),
						),
					),
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'Alba' => 'Alba',
						'Arad' => 'Arad',
						'Arges' => 'Arges',
						'Bacau' => 'Bacau',
						'Bihor' => 'Bihor',
						'Bistrita-Nasaud' => 'Bistrita-Nasaud',
						'Botosani' => 'Botosani',
						'Brasov' => 'Brasov',
						'Braila' => 'Braila',
						'Bucuresti' => 'Bucuresti',
						'Buzau' => 'Buzau',
						'Caras-Severin' => 'Caras-Severin',
						'Cluj' => 'Cluj',
						'Constanta' => 'Constanta',
						'Covasna' => 'Covasna',
						'Dimbovita' => 'Dimbovita',
						'Dolj' => 'Dolj',
						'Galati' => 'Galati',
						'Gorj' => 'Gorj',
						'Harghita' => 'Harghita',
						'Hunedoara' => 'Hunedoara',
						'Ialomita' => 'Ialomita',
						'Iasi' => 'Iasi',
						'Ilfov' => 'Ilfov',
						'Maramures' => 'Maramures',
						'Mehedinti' => 'Mehedinti',
						'Mures' => 'Mures',
						'Neamt' => 'Neamt',
						'Olt' => 'Olt',
						'Prahova' => 'Prahova',
						'Satu_Mare' => 'Satu_Mare',
						'Salaj' => 'Salaj',
						'Sibiu' => 'Sibiu',
						'Suceava' => 'Suceava',
						'Teleorman' => 'Teleorman',
						'Timis' => 'Timis',
						'Tulcea' => 'Tulcea',
						'Vaslui' => 'Vaslui',
						'Vilcea' => 'Vilcea',
						'Vrancea' => 'Vrancea',
						'Calarasi' => 'Calarasi',
						'Giurgiu' => 'Giurgiu',
					),
					'default_value' => array(
					),
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 1,
					'ajax' => 0,
					'return_format' => 'value',
					'placeholder' => '',
				),
				array(
					'key' => 'field_5d2ccdfa3cd84',
					'label' => 'Extindere',
					'name' => 'extindere',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5d0bfb256cebc',
								'operator' => '==',
								'value' => 'extindere',
							),
						),
					),
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'locala' => 'locala',
						'regionala' => 'regionala',
						'multinationala' => 'multinationala',
					),
					'default_value' => array(
					),
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'return_format' => 'value',
					'ajax' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_5d2cce0e3cd85',
					'label' => 'Head Office',
					'name' => 'head_office',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5d0bfb256cebc',
								'operator' => '==',
								'value' => 'head-office',
							),
						),
					),
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5d2cce2b3cd86',
					'label' => 'Cifra de afaceri',
					'name' => 'cifra_de_afaceri',
					'type' => 'number',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5d0bfb256cebc',
								'operator' => '==',
								'value' => 'cifra_afaceri',
							),
						),
					),
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'min' => '',
					'max' => '',
					'step' => '',
				),
				array(
					'key' => 'field_5d2cd3623855a',
					'label' => 'Numar angajati',
					'name' => 'numar_angajati',
					'type' => 'number',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5d0bfb256cebc',
								'operator' => '==',
								'value' => 'nr-angajati',
							),
						),
					),
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'min' => '',
					'max' => '',
					'step' => '',
				),
			),
		),
		array(
			'key' => 'field_5d2cd57abcea3',
			'label' => 'Descriere companie',
			'name' => 'descriere_companie',
			'type' => 'wysiwyg',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5d0bfb256cebc',
						'operator' => '==',
						'value' => 'descriere',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 0,
			'delay' => 0,
		),
		array(
			'key' => 'field_5d2cd59dbcea4',
			'label' => 'Descriere domeniu sintetic',
			'name' => 'descriere_domeniu_sintetic',
			'type' => 'wysiwyg',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5d0bfb256cebc',
						'operator' => '==',
						'value' => 'domeniu-sintetic',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 0,
			'delay' => 0,
		),
		array(
			'key' => 'field_5d2cd5b3bcea5',
			'label' => 'Descriere domeniu pe larg',
			'name' => 'descriere_domeniu_larg',
			'type' => 'wysiwyg',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5d0bfb256cebc',
						'operator' => '==',
						'value' => 'domeniu-larg',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'default_value' => '',
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 0,
			'delay' => 0,
			'acfe_validate' => '',
			'acfe_update' => '',
		),
		array(
			'key' => 'field_5d4aaa37ab898',
			'label' => 'Note si comentarii libere',
			'name' => 'note_comentarii',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => 3,
			'new_lines' => 'br',
			'acfe_validate' => '',
			'acfe_update' => '',
		),
		array(
			'key' => 'field_5d3a180b927ba',
			'label' => 'Link-uri',
			'name' => 'link-uri_companie',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'collapsed' => '',
			'min' => 0,
			'max' => 0,
			'layout' => 'table',
			'button_label' => '',
			'sub_fields' => array(
				array(
					'key' => 'field_5d3a1832927bb',
					'label' => 'Link',
					'name' => 'link',
					'type' => 'url',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'default_value' => '',
					'placeholder' => 'ex	https://www.facebook.com/managero',
					'acfe_validate' => '',
					'acfe_update' => '',
				),
				array(
					'key' => 'field_5d3a183f927bc',
					'label' => 'Titlu',
					'name' => 'titlu',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'default_value' => '',
					'placeholder' => 'ex facebook',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'acfe_validate' => '',
					'acfe_update' => '',
				),
			),
		),
		array(
			'key' => 'field_5d3a188312ab3',
			'label' => 'Imagine profil',
			'name' => 'imagine_profil_companie',
			'type' => 'image_aspect_ratio_crop',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'aspect_ratio_width' => 240,
			'aspect_ratio_height' => 120,
			'return_format' => 'id',
			'preview_size' => 'medium',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
			'acfe_validate' => '',
			'acfe_update' => '',
		),
		array(
			'key' => 'field_5d4d257c7c162',
			'label' => 'Salveaza profil companie',
			'name' => 'salveaza_profil_companie',
			'type' => 'button',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'button_value' => 'Salveaza profil companie',
			'button_attributes' => array(
				'button_type' => 'button',
				'button_class' => 'btn-standard',
				'button_id' => 'salveaza_profil_companie',
			),
			'button_wrapper' => array(
				'button_before' => '',
				'button_after' => '',
			),
			'acfe_validate' => '',
			'acfe_update' => '',
		),
		array(
			'key' => 'field_5d4825f7251e8',
			'label' => 'Salveaza profil companie ca',
			'name' => 'salveaza_profil_companie_ca',
			'type' => 'button',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'button_value' => 'Salveaza profil companie',
			'button_attributes' => array(
				'button_type' => 'button',
				'button_class' => 'btn-standard',
				'button_id' => 'trigger_salveaza_profil_companie_ca',
			),
			'button_wrapper' => array(
				'button_before' => '',
				'button_after' => '',
			),
			'acfe_validate' => '',
			'acfe_update' => '',
		),
		array(
			'key' => 'field_5d48262a251e9',
			'label' => 'Date profil companie',
			'name' => 'date_profil_companie',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => 'wrap-salveaza-profil-companie',
			),
			'acfe_permissions' => '',
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_5d48264f251ea',
					'label' => 'Nume profil companie',
					'name' => 'nume_profil_companie',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'acfe_validate' => '',
					'acfe_update' => '',
				),
				array(
					'key' => 'field_5d482658251eb',
					'label' => 'Descriere profil companie',
					'name' => 'descriere_profil_companie',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'default_value' => '',
					'placeholder' => '',
					'maxlength' => '',
					'rows' => 2,
					'new_lines' => '',
					'acfe_validate' => '',
					'acfe_update' => '',
				),
				array(
					'key' => 'field_5d482717b06ea',
					'label' => 'OK',
					'name' => 'ok',
					'type' => 'button',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'button_value' => 'OK',
					'button_attributes' => array(
						'button_type' => 'button',
						'button_class' => 'btn-standard',
						'button_id' => 'salveaza_profil_companie_ca',
					),
					'button_wrapper' => array(
						'button_before' => '',
						'button_after' => '',
					),
					'acfe_validate' => '',
					'acfe_update' => '',
				),
			),
		),
		array(
			'key' => 'field_5d38459692fdc',
			'label' => 'Job',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5d4bfc2e43023',
			'label' => 'Profil job',
			'name' => 'profil_job',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '100',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_5d4bfc6343024',
					'label' => 'Alege profil job',
					'name' => 'alege_profil_job',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'choices' => array(
					),
					'default_value' => array(
					),
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'return_format' => 'value',
					'acfe_validate' => '',
					'acfe_update' => '',
					'ajax' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_5d4bfd7843025',
					'label' => 'Aplica profil job',
					'name' => 'aplica_profil_job',
					'type' => 'button',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'button_value' => 'Aplica profil job',
					'button_attributes' => array(
						'button_type' => 'button',
						'button_class' => '',
						'button_id' => 'aplica_profil_job',
					),
					'button_wrapper' => array(
						'button_before' => '',
						'button_after' => '',
					),
					'acfe_validate' => '',
					'acfe_update' => '',
				),
			),
		),
		array(
			'key' => 'field_5d0a54284bb00',
			'label' => 'Post',
			'name' => 'post_job',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'Postul oferit',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5d0a54e74bb01',
			'label' => 'Pozitia ierarhica',
			'name' => 'pozitia_ierarhica',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_5d0a55154bb02',
					'label' => 'Nivelul ierarhic',
					'name' => 'nivelul_ierarhic',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'ceo' => 'ceo',
						'ceo -1' => 'ceo -1',
						'ceo -2' => 'ceo -2',
						'middle management' => 'middle management',
						'board executive' => 'board executive',
						'board non-executive' => 'board non-executive',
						'alt nivel' => 'alt nivel',
					),
					'default_value' => array(
					),
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'return_format' => 'value',
					'ajax' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_5d0a55504bb03',
					'label' => 'Cui este subordonat',
					'name' => 'cui_este_subordonat',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => 'numele pozitiei',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5d0a55f14bb04',
					'label' => 'Cati subordonati are in total',
					'name' => 'subordonati_total',
					'type' => 'number',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => 'numarul de subordonati',
					'prepend' => '',
					'append' => '',
					'min' => '',
					'max' => '',
					'step' => '',
				),
			),
		),
		array(
			'key' => 'field_5d0a6b02fa2bd',
			'label' => 'Domeniu',
			'name' => 'domeniu',
			'type' => 'taxonomy',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '34',
				'class' => '',
				'id' => '',
			),
			'taxonomy' => 'sector',
			'field_type' => 'checkbox',
			'add_term' => 0,
			'save_terms' => 1,
			'load_terms' => 0,
			'return_format' => 'object',
			'multiple' => 0,
			'allow_null' => 0,
		),
		array(
			'key' => 'field_5d0a5c6a43cc6',
			'label' => 'Locatia jobului',
			'name' => 'locatia_jobului',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '16',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'Alba' => 'Alba',
				'Arad' => 'Arad',
				'Arges' => 'Arges',
				'Bacau' => 'Bacau',
				'Bihor' => 'Bihor',
				'Bistrita-Nasaud' => 'Bistrita-Nasaud',
				'Botosani' => 'Botosani',
				'Braila' => 'Braila',
				'Brasov' => 'Brasov',
				'Bucuresti' => 'Bucuresti',
				'Buzau' => 'Buzau',
				'Calarasi' => 'Calarasi',
				'Caras	Severin' => 'Caras	Severin',
				'Caras-Severin' => 'Caras-Severin',
				'Cluj' => 'Cluj',
				'Constanta' => 'Constanta',
				'Covasna' => 'Covasna',
				'Dambovita' => 'Dambovita',
				'Dolj' => 'Dolj',
				'Galati' => 'Galati',
				'Giurgiu' => 'Giurgiu',
				'Gorj' => 'Gorj',
				'Harghita' => 'Harghita',
				'Hargita' => 'Hargita',
				'Hunedoara' => 'Hunedoara',
				'Ialomita' => 'Ialomita',
				'Iasi' => 'Iasi',
				'Ilfov' => 'Ilfov',
				'Maramures' => 'Maramures',
				'Mehedinti' => 'Mehedinti',
				'Mures' => 'Mures',
				'Neamt' => 'Neamt',
				'Olt' => 'Olt',
				'Prahova' => 'Prahova',
				'Salaj' => 'Salaj',
				'Satu	Mare' => 'Satu	Mare',
				'Sibiu' => 'Sibiu',
				'Suceava' => 'Suceava',
				'Teleorman' => 'Teleorman',
				'Timis' => 'Timis',
				'Tulcea' => 'Tulcea',
				'Valcea' => 'Valcea',
				'Vaslui' => 'Vaslui',
				'Vrancea' => 'Vrancea',
			),
			'default_value' => array(
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 1,
			'ajax' => 0,
			'return_format' => 'label',
			'placeholder' => '',
		),
		array(
			'key' => 'field_5d0a562cd4632',
			'label' => 'Descrierea sintetica a jobului',
			'name' => 'descrierea_sintetica_a_jobului',
			'type' => 'wysiwyg',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'default_value' => '',
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 0,
			'delay' => 0,
			'acfe_validate' => '',
			'acfe_update' => '',
		),
		array(
			'key' => 'field_5d0a5cc8f57b8',
			'label' => 'Cerinte job',
			'name' => 'cerinte_job',
			'type' => 'wysiwyg',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 0,
			'delay' => 0,
		),
		array(
			'key' => 'field_5d0a5dbef57b9',
			'label' => 'Oferta',
			'name' => 'oferta',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_5d0a5ddaf57ba',
					'label' => 'Salariu',
					'name' => 'salariu_oferit_job',
					'type' => 'number',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => 'Salariu oferit',
					'prepend' => '',
					'append' => '',
					'min' => '',
					'max' => '',
					'step' => '',
				),
				array(
					'key' => 'field_5d0a5dfaf57bb',
					'label' => 'Descriere sintetica a ofertei',
					'name' => 'descriere_oferta',
					'type' => 'wysiwyg',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'tabs' => 'all',
					'toolbar' => 'full',
					'media_upload' => 0,
					'delay' => 0,
				),
			),
		),
		array(
			'key' => 'field_5d0a5f83f57bd',
			'label' => 'Cum sa aplice',
			'name' => 'cum_sa_aplice',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_5d0a603338bf9',
					'label' => 'Mod aplicare',
					'name' => 'mod_aplicare',
					'type' => 'checkbox',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'Managero' => 'Managero',
						'E-mail' => 'E-mail',
					),
					'allow_custom' => 0,
					'default_value' => array(
					),
					'layout' => 'horizontal',
					'toggle' => 0,
					'return_format' => 'value',
					'save_custom' => 0,
				),
				array(
					'key' => 'field_5d0a607a38bfa',
					'label' => 'Instructiuni aplicare pe email',
					'name' => 'instructiuni_aplicare',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5d0a603338bf9',
								'operator' => '==',
								'value' => 'E-mail',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => 'persoana de contact, e-mail, informatii...',
					'maxlength' => '',
					'rows' => 6,
					'new_lines' => 'br',
				),
			),
		),
		array(
			'key' => 'field_5d0a61274d1c0',
			'label' => 'Filtre candidati',
			'name' => 'filtre_candidati',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_5d0a61d34d1c1',
					'label' => 'Profil minimal',
					'name' => 'profil_minimal',
					'type' => 'group',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'layout' => 'block',
					'sub_fields' => array(
					),
				),
				array(
					'key' => 'field_5d0a61e04d1c2',
					'label' => 'Varsta',
					'name' => 'varsta_scm',
					'type' => 'number',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'min' => '',
					'max' => '',
					'step' => '',
				),
				array(
					'key' => 'field_5d0a61ec4d1c3',
					'label' => 'Sex',
					'name' => 'sex_scm',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'masculin' => 'Masculin',
						'feminin' => 'Feminin',
					),
					'default_value' => array(
					),
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'return_format' => 'value',
					'ajax' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_5d0a69bcdae4a',
					'label' => 'Salariu minim acceptat',
					'name' => 'salariu_minim_scm',
					'type' => 'number',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => 'Salariu minim acceptat',
					'prepend' => '',
					'append' => '',
					'min' => '',
					'max' => '',
					'step' => '',
				),
			),
		),
		array(
			'key' => 'field_5d0a6a091cadb',
			'label' => 'Fisiere atasate',
			'name' => 'fisiere_atasate',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'collapsed' => '',
			'min' => 0,
			'max' => 0,
			'layout' => 'table',
			'button_label' => '',
			'sub_fields' => array(
				array(
					'key' => 'field_5d0a6a151cadc',
					'label' => 'Fisier',
					'name' => 'fisier',
					'type' => 'file',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'url',
					'library' => 'all',
					'min_size' => '',
					'max_size' => '',
					'mime_types' => '',
				),
				array(
					'key' => 'field_5d0a6a301cadd',
					'label' => 'Denumire',
					'name' => 'denumire',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
			),
		),
		array(
			'key' => 'field_5d0a6a80b2a9b',
			'label' => 'Galerie',
			'name' => 'galerie_imagini',
			'type' => 'gallery',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'return_format' => 'array',
			'preview_size' => 'medium',
			'insert' => 'append',
			'library' => 'all',
			'min' => '',
			'max' => '',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
			'acfe_validate' => '',
			'acfe_update' => '',
		),
		array(
			'key' => 'field_5d0a5e38f57bc',
			'label' => 'Comentarii job',
			'name' => 'comentarii',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => 5,
			'new_lines' => '',
			'acfe_validate' => '',
			'acfe_update' => '',
		),
		array(
			'key' => 'field_5d0a6a4237524',
			'label' => 'Imagine Cover',
			'name' => 'imagine_cover',
			'type' => 'image_aspect_ratio_crop',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'aspect_ratio_width' => 1100,
			'aspect_ratio_height' => 300,
			'return_format' => 'id',
			'preview_size' => 'full',
			'library' => 'all',
			'min_width' => 1100,
			'min_height' => 300,
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
			'acfe_validate' => '',
			'acfe_update' => '',
		),
		array(
			'key' => 'field_5d4d42b7cde19',
			'label' => 'Salveaza profil job',
			'name' => 'salveaza_profil_job',
			'type' => 'button',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'button_value' => 'Salveaza profil job',
			'button_attributes' => array(
				'button_type' => 'button',
				'button_class' => '',
				'button_id' => 'salveaza_profil_job',
			),
			'button_wrapper' => array(
				'button_before' => '',
				'button_after' => '',
			),
			'acfe_validate' => '',
			'acfe_update' => '',
		),
		array(
			'key' => 'field_5d48236a22a1c',
			'label' => 'Salveaza profil job ca',
			'name' => 'salveaza_profil_companie_ca',
			'type' => 'button',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'button_value' => 'Salveaza profil job',
			'button_attributes' => array(
				'button_type' => 'button',
				'button_class' => '',
				'button_id' => 'salveaza_profil_job',
			),
			'button_wrapper' => array(
				'button_before' => '',
				'button_after' => '',
			),
			'acfe_validate' => '',
			'acfe_update' => '',
		),
		array(
			'key' => 'field_5d4823f222a1d',
			'label' => 'Date profil job',
			'name' => 'date_profil_job',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => 'wrap-salveaza-profil-job',
			),
			'acfe_permissions' => '',
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_5d4823fd22a1e',
					'label' => 'Nume profil job',
					'name' => 'nume_profil_job',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'acfe_validate' => '',
					'acfe_update' => '',
				),
				array(
					'key' => 'field_5d48241722a1f',
					'label' => 'Descriere profil job',
					'name' => 'descriere_profil_job',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'default_value' => '',
					'placeholder' => '',
					'maxlength' => '',
					'rows' => 2,
					'new_lines' => '',
					'acfe_validate' => '',
					'acfe_update' => '',
				),
				array(
					'key' => 'field_5d48242322a20',
					'label' => 'Ok',
					'name' => 'ok',
					'type' => 'button',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'button_value' => 'Ok',
					'button_attributes' => array(
						'button_type' => 'submit',
						'button_class' => '',
						'button_id' => 'salveaza_profil_job',
					),
					'button_wrapper' => array(
						'button_before' => '',
						'button_after' => '',
					),
					'acfe_validate' => '',
					'acfe_update' => '',
				),
			),
		),
		array(
			'key' => 'field_5d496a147165c',
			'label' => 'Date template',
			'name' => 'date_template',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => 'wrap-save-template',
			),
			'acfe_permissions' => '',
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_5d496a2e7165d',
					'label' => 'Nume template',
					'name' => 'nume_template',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'acfe_validate' => '',
					'acfe_update' => '',
				),
				array(
					'key' => 'field_5d496ab97165e',
					'label' => 'Descriere template',
					'name' => 'descriere_template',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'default_value' => '',
					'placeholder' => '',
					'maxlength' => '',
					'rows' => 2,
					'new_lines' => '',
					'acfe_validate' => '',
					'acfe_update' => '',
				),
			),
		),
		array(
			'key' => 'field_5d482473ea89c',
			'label' => 'Salveaza template anunt',
			'name' => 'salveaza_template_anunt',
			'type' => 'button',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'button_value' => 'Salveaza template anunt',
			'button_attributes' => array(
				'button_type' => 'button',
				'button_class' => 'btn-standard',
				'button_id' => 'salveaza_template_anunt',
			),
			'button_wrapper' => array(
				'button_before' => '',
				'button_after' => '',
			),
			'acfe_validate' => '',
			'acfe_update' => '',
		),
		array(
			'key' => 'field_5d4824cbea89d',
			'label' => 'Salveaza template anunt ca',
			'name' => 'salveaza_template_anunt_ca',
			'type' => 'button',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'button_value' => 'Salveaza template anunt ca',
			'button_attributes' => array(
				'button_type' => 'button',
				'button_class' => 'btn-standard',
				'button_id' => 'salveaza_template_anunt_ca',
			),
			'button_wrapper' => array(
				'button_before' => '',
				'button_after' => '',
			),
			'acfe_validate' => '',
			'acfe_update' => '',
		),
		array(
			'key' => 'field_5d4824e9ea89e',
			'label' => 'Delete template anunt',
			'name' => 'delete_template_anunt',
			'type' => 'button',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'button_value' => 'Delete template anunt',
			'button_attributes' => array(
				'button_type' => 'button',
				'button_class' => 'btn-standard',
				'button_id' => 'delete_template_anunt',
			),
			'button_wrapper' => array(
				'button_before' => '',
				'button_after' => '',
			),
			'acfe_validate' => '',
			'acfe_update' => '',
		),
		array(
			'key' => 'field_5d4825135ba9d',
			'label' => 'Salveaza template anunt ca',
			'name' => 'date_template_anunt_ca',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => 'wrap-save-as-template',
			),
			'acfe_permissions' => '',
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_5d48252f5ba9e',
					'label' => 'Nume template',
					'name' => 'nume_template_as',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'acfe_validate' => '',
					'acfe_update' => '',
				),
				array(
					'key' => 'field_5d4825515ba9f',
					'label' => 'Descriere template',
					'name' => 'descriere_template_as',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'default_value' => '',
					'placeholder' => '',
					'maxlength' => '',
					'rows' => 2,
					'new_lines' => '',
					'acfe_validate' => '',
					'acfe_update' => '',
				),
				array(
					'key' => 'field_5d4825655baa0',
					'label' => 'OK',
					'name' => 'ok',
					'type' => 'button',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'button_value' => 'OK',
					'button_attributes' => array(
						'button_type' => 'button',
						'button_class' => 'btn-standard',
						'button_id' => 'ok_salveaza_ca',
					),
					'button_wrapper' => array(
						'button_before' => '',
						'button_after' => '',
					),
					'acfe_validate' => '',
					'acfe_update' => '',
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'job',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
	'acfe_display_title' => '',
	'acfe_autosync' => array(
		0 => 'php',
	),
	'acfe_permissions' => '',
	'acfe_note' => '',
	'acfe_meta' => '',
	'modified' => 1565548024,
));

endif;