<?php 

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_job_template',
	'title' => 'Template Job',
	'fields' => array(
		array(
			'key' => 'template_job_content_01',
			'label' => 'Template',
			'name' => 'template_job_content',
			'type' => 'flexible_content',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'acfe_flexible_stylised_button' => 0,
			'acfe_flexible_hide_empty_message' => 0,
			'acfe_flexible_empty_message' => '',
			'acfe_flexible_layouts_thumbnails' => 0,
			'acfe_flexible_layouts_templates' => 0,
			'acfe_flexible_close_button' => 0,
			'acfe_flexible_copy_paste' => 0,
			'acfe_flexible_modal_edition' => 1,
			'acfe_flexible_modal' => array(
				'acfe_flexible_modal_enabled' => '0',
			),
			'layouts' => array(
				'layout_5d39848f107f7' => array(
					'key' => 'layout_template_job_01',
					'name' => 'template_job',
					'label' => 'Template job',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'post_job_template_01',
							'label' => 'Post',
							'name' => 'post_job_template',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'acfe_permissions' => '',
							'default_value' => '',
							'placeholder' => 'Postul oferit',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'acfe_validate' => false,
							'acfe_update' => false,
						),
						array(
							'key' => 'pozitia_ierarhica_template_01',
							'label' => 'Pozitia ierarhica',
							'name' => 'pozitia_ierarhica_template',
							'type' => 'group',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'acfe_permissions' => '',
							'layout' => 'block',
							'sub_fields' => array(
								array(
									'key' => 'nivelul_ierarhic_01',
									'label' => 'Nivelul ierarhic',
									'name' => 'nivelul_ierarhic',
									'type' => 'select',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '33',
										'class' => '',
										'id' => '',
									),
									'acfe_permissions' => '',
									'choices' => array(
										'ceo' => 'ceo',
										'ceo -1' => 'ceo -1',
										'ceo -2' => 'ceo -2',
										'middle management' => 'middle management',
										'board executive' => 'board executive',
										'board non-executive' => 'board non-executive',
										'alt nivel' => 'alt nivel',
									),
									'default_value' => array(
									),
									'allow_null' => 0,
									'multiple' => 0,
									'ui' => 0,
									'return_format' => 'value',
									'acfe_validate' => '',
									'acfe_update' => '',
									'ajax' => 0,
									'placeholder' => '',
								),
								array(
									'key' => 'cui_este_subordonat_01',
									'label' => 'Cui este subordonat',
									'name' => 'cui_este_subordonat',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '33',
										'class' => '',
										'id' => '',
									),
									'acfe_permissions' => '',
									'default_value' => '',
									'placeholder' => 'numele pozitiei',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
									'acfe_validate' => '',
									'acfe_update' => '',
								),
								array(
									'key' => 'subordonati_total_01',
									'label' => 'Cati subordonati are in total',
									'name' => 'subordonati_total',
									'type' => 'number',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '33',
										'class' => '',
										'id' => '',
									),
									'acfe_permissions' => '',
									'default_value' => '',
									'placeholder' => 'numarul de subordonati',
									'prepend' => '',
									'append' => '',
									'min' => '',
									'max' => '',
									'step' => '',
									'acfe_validate' => '',
									'acfe_update' => '',
								),
							),
						),
						array(
							'key' => 'domeniu_template_01',
							'label' => 'Domeniu',
							'name' => 'domeniu_template',
							'type' => 'taxonomy',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '34',
								'class' => '',
								'id' => '',
							),
							'acfe_permissions' => '',
							'taxonomy' => 'sector',
							'field_type' => 'checkbox',
							'allow_null' => 0,
							'add_term' => 0,
							'save_terms' => 1,
							'load_terms' => 0,
							'return_format' => 'object',
							'acfe_bidirectional' => array(
								'acfe_bidirectional_enabled' => '0',
								'acfe_bidirectional_related' => '',
							),
							'acfe_validate' => false,
							'acfe_update' => false,
							'multiple' => 0,
						),
						array(
							'key' => 'locatia_jobului_template_01',
							'label' => 'Locatia jobului',
							'name' => 'locatia_jobului_template',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '19',
								'class' => '',
								'id' => '',
							),
							'acfe_permissions' => '',
							'choices' => array(
								'Alba' => 'Alba',
								'Arad' => 'Arad',
								'Arges' => 'Arges',
								'Bacau' => 'Bacau',
								'Bihor' => 'Bihor',
								'Bistrita-Nasaud' => 'Bistrita-Nasaud',
								'Botosani' => 'Botosani',
								'Braila' => 'Braila',
								'Brasov' => 'Brasov',
								'Bucuresti' => 'Bucuresti',
								'Buzau' => 'Buzau',
								'Calarasi' => 'Calarasi',
								'Caras	Severin' => 'Caras	Severin',
								'Caras-Severin' => 'Caras-Severin',
								'Cluj' => 'Cluj',
								'Constanta' => 'Constanta',
								'Covasna' => 'Covasna',
								'Dambovita' => 'Dambovita',
								'Dolj' => 'Dolj',
								'Galati' => 'Galati',
								'Giurgiu' => 'Giurgiu',
								'Gorj' => 'Gorj',
								'Harghita' => 'Harghita',
								'Hargita' => 'Hargita',
								'Hunedoara' => 'Hunedoara',
								'Ialomita' => 'Ialomita',
								'Iasi' => 'Iasi',
								'Ilfov' => 'Ilfov',
								'Maramures' => 'Maramures',
								'Mehedinti' => 'Mehedinti',
								'Mures' => 'Mures',
								'Neamt' => 'Neamt',
								'Olt' => 'Olt',
								'Prahova' => 'Prahova',
								'Salaj' => 'Salaj',
								'Satu	Mare' => 'Satu	Mare',
								'Sibiu' => 'Sibiu',
								'Suceava' => 'Suceava',
								'Teleorman' => 'Teleorman',
								'Timis' => 'Timis',
								'Tulcea' => 'Tulcea',
								'Valcea' => 'Valcea',
								'Vaslui' => 'Vaslui',
								'Vrancea' => 'Vrancea',
							),
							'default_value' => array(
							),
							'allow_null' => 0,
							'multiple' => 0,
							'ui' => 1,
							'ajax' => 0,
							'return_format' => 'label',
							'acfe_validate' => false,
							'acfe_update' => false,
							'placeholder' => '',
						),
						array(
							'key' => 'descrierea_sintetica_job_template_01',
							'label' => 'Descrierea sintetica a jobului',
							'name' => 'descrierea_sintetica_job_template',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'acfe_permissions' => '',
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 0,
							'delay' => 0,
							'acfe_validate' => false,
							'acfe_update' => false,
						),
						array(
							'key' => 'cerinte_job_01',
							'label' => 'Cerinte job',
							'name' => 'cerinte_job',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'acfe_permissions' => '',
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 0,
							'delay' => 0,
							'acfe_validate' => false,
							'acfe_update' => false,
						),
						array(
							'key' => 'field_5d397fbad286d',
							'label' => 'Oferta',
							'name' => 'oferta_template',
							'type' => 'group',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'acfe_permissions' => '',
							'layout' => 'block',
							'sub_fields' => array(
								array(
									'key' => 'field_5d397fd7d286e',
									'label' => 'Salariu',
									'name' => 'salariu_oferit_job',
									'type' => 'number',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'acfe_permissions' => '',
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'min' => '',
									'max' => '',
									'step' => '',
									'acfe_validate' => '',
									'acfe_update' => '',
								),
								array(
									'key' => 'field_5d397ff6d286f',
									'label' => 'Descriere sintetica a ofertei',
									'name' => 'descriere_oferta',
									'type' => 'wysiwyg',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'acfe_permissions' => '',
									'default_value' => '',
									'tabs' => 'all',
									'toolbar' => 'full',
									'media_upload' => 0,
									'delay' => 0,
									'acfe_validate' => '',
									'acfe_update' => '',
								),
							),
						),
						array(
							'key' => 'field_5d398008d2870',
							'label' => 'Cum sa aplice',
							'name' => 'cum_sa_aplice',
							'type' => 'group',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'acfe_permissions' => '',
							'layout' => 'block',
							'sub_fields' => array(
								array(
									'key' => 'field_5d39801ed2871',
									'label' => 'Mod aplicare',
									'name' => 'mod_aplicare',
									'type' => 'checkbox',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'acfe_permissions' => '',
									'choices' => array(
										'Managero' => 'Managero',
										'E-mail' => 'E-mail',
									),
									'allow_custom' => 0,
									'default_value' => array(
									),
									'layout' => 'horizontal',
									'toggle' => 0,
									'return_format' => 'value',
									'acfe_validate' => '',
									'acfe_update' => '',
									'save_custom' => 0,
								),
							),
						),
						array(
							'key' => 'field_5d39804dd2872',
							'label' => 'Filtre candidati',
							'name' => 'filtre_candidati_template',
							'type' => 'group',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'acfe_permissions' => '',
							'layout' => 'block',
							'sub_fields' => array(
								array(
									'key' => 'field_5d39807ad2874',
									'label' => 'Varsta',
									'name' => 'varsta_scm',
									'type' => 'number',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '33',
										'class' => '',
										'id' => '',
									),
									'acfe_permissions' => '',
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'min' => '',
									'max' => '',
									'step' => '',
									'acfe_validate' => '',
									'acfe_update' => '',
								),
								array(
									'key' => 'field_5d398091d2875',
									'label' => 'Sex',
									'name' => 'sex_scm',
									'type' => 'select',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '33',
										'class' => '',
										'id' => '',
									),
									'acfe_permissions' => '',
									'choices' => array(
										'masculin' => 'Masculin',
										'feminin' => 'Feminin',
										'nespecificat' => 'Nespecificat',
									),
									'default_value' => array(
									),
									'allow_null' => 0,
									'multiple' => 0,
									'ui' => 0,
									'return_format' => 'value',
									'acfe_validate' => '',
									'acfe_update' => '',
									'ajax' => 0,
									'placeholder' => '',
								),
								array(
									'key' => 'field_5d3980dbd2876',
									'label' => 'Salariu minim acceptat',
									'name' => 'salariu_minim_scm',
									'type' => 'number',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '33',
										'class' => '',
										'id' => '',
									),
									'acfe_permissions' => '',
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'min' => '',
									'max' => '',
									'step' => '',
									'acfe_validate' => '',
									'acfe_update' => '',
								),
							),
						),
						array(
							'key' => 'field_5d3980fe9393d',
							'label' => 'Fisiere atasate',
							'name' => 'fiisiere_atasate_template',
							'type' => 'repeater',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'acfe_permissions' => '',
							'collapsed' => '',
							'min' => 0,
							'max' => 0,
							'layout' => 'table',
							'button_label' => '',
							'jpn-tabs' => 0,
							'sub_fields' => array(
								array(
									'key' => 'field_5d39811a9393e',
									'label' => 'Fisiere',
									'name' => 'fisiere',
									'type' => 'file',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'acfe_permissions' => '',
									'return_format' => 'url',
									'library' => 'all',
									'min_size' => '',
									'max_size' => '',
									'mime_types' => '',
									'acfe_validate' => '',
									'acfe_update' => '',
								),
								array(
									'key' => 'field_5d39817a9393f',
									'label' => 'Denumire',
									'name' => 'denumire',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'acfe_permissions' => '',
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
									'acfe_validate' => '',
									'acfe_update' => '',
								),
							),
						),
						array(
							'key' => 'field_5d39818793940',
							'label' => 'Galerie',
							'name' => 'galerie_imagini_job_template',
							'type' => 'gallery',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'acfe_permissions' => '',
							'return_format' => 'array',
							'preview_size' => 'medium',
							'insert' => 'append',
							'library' => 'all',
							'min' => '',
							'max' => '',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
							'acfe_validate' => false,
							'acfe_update' => false,
						),
						array(
							'key' => 'field_5d3981ae93941',
							'label' => 'Comentarii job',
							'name' => 'comentarii_job_template',
							'type' => 'textarea',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'acfe_permissions' => '',
							'default_value' => '',
							'placeholder' => '',
							'maxlength' => '',
							'rows' => '',
							'new_lines' => '',
							'acfe_validate' => false,
							'acfe_update' => false,
						),
						array(
							'key' => 'field_5d3981c993942',
							'label' => 'Imagine Cover',
							'name' => 'imagine_cover_job_template',
							'type' => 'image_aspect_ratio_crop',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'acfe_permissions' => '',
							'aspect_ratio_width' => 1100,
							'aspect_ratio_height' => 300,
							'return_format' => 'url',
							'preview_size' => 'large',
							'library' => 'all',
							'min_width' => 1100,
							'min_height' => 300,
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
							'acfe_validate' => '',
							'acfe_update' => '',
						),
						array(
							'key' => 'field_5d398b71e1db3',
							'label' => 'Date template',
							'name' => 'date_profil',
							'type' => 'group',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'acfe_permissions' => '',
							'layout' => 'block',
							'sub_fields' => array(
								array(
									'key' => 'field_5d3989f5fb8c1',
									'label' => 'Nume template',
									'name' => 'nume_profil',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '48',
										'class' => '',
										'id' => '',
									),
									'acfe_permissions' => '',
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
									'acfe_validate' => false,
									'acfe_update' => false,
								),
								array(
									'key' => 'field_5d398a0cfb8c2',
									'label' => 'Descriere template',
									'name' => 'descriere_profil',
									'type' => 'textarea',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '50',
										'class' => '',
										'id' => '',
									),
									'acfe_permissions' => '',
									'default_value' => '',
									'placeholder' => '',
									'maxlength' => '',
									'rows' => 2,
									'new_lines' => '',
									'acfe_validate' => false,
									'acfe_update' => false,
								),
							),
						),
						array(
							'key' => 'field_5d3988c6d2bdc',
							'label' => 'Preview',
							'name' => 'preview_template',
							'type' => 'button',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '50',
								'class' => '',
								'id' => '',
							),
							'acfe_permissions' => '',
							'button_value' => 'Prewiew',
							'button_attributes' => array(
								'button_type' => 'button',
								'button_class' => 'preview-template',
								'button_id' => '',
							),
							'button_wrapper' => array(
								'button_before' => '',
								'button_after' => '',
							),
							'acfe_validate' => '',
							'acfe_update' => '',
						),
						array(
							'key' => 'field_5d3988b4d2bdb',
							'label' => 'Salveaza',
							'name' => 'salveaza _template',
							'type' => 'button',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '50',
								'class' => '',
								'id' => '',
							),
							'acfe_permissions' => '',
							'button_value' => 'Salveaza',
							'button_attributes' => array(
								'button_type' => 'submit',
								'button_class' => '',
								'button_id' => '',
							),
							'button_wrapper' => array(
								'button_before' => '',
								'button_after' => '',
							),
							'acfe_validate' => '',
							'acfe_update' => '',
						),
					),
					'min' => '',
					'max' => '',
				),
			),
			'button_label' => 'Adauga un nou template',
			'min' => '',
			'max' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'employer',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'left',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
	'acfe_display_title' => '',
	'acfe_autosync' => array(
		0 => 'php',
	),
	'acfe_permissions' => '',
	'acfe_note' => '',
	'acfe_meta' => '',
	'modified' => 1564401301,
));

endif;